char *str = "\n-h Show this help."
            "\n-i Init a new empty database. For example:"
                "\n\tmemo -i 'memo.csv'"
                "\n\tCreate a new empty database with the name 'memo.csv'"
            "\n-a Append at the end of the database the following message."
                "\n\tmemo -a 'This message will be included at the end of the database'"
            "\n-s Search and find specific entries in the database."
                "\n\tmemo -s '09-11-2022' will show all entries at a this given date."
                "\n\tmemo -s 'programming' will show all entries containing the word"
                "\n\t'programming'."
            "\n-d Delete an entry in the database."
                "\n\tmemo -d 123 will delete entry number 123.";